config/routes.rb
Rails.application.routes.draw do
  root 'polls#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :polls
  get 'answers/:uuid/new', controller: 'answers', action: 'new', as: 'vote'
  resources :answers, only: :create
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :poll

  validates_presence_of :option
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates_presence_of :title
  validate :minimum_number_of_answer_options

  before_create :assign_uuid

  private

  def assign_uuid
    self.uuid = SecureRandom.uuid
  end

  def minimum_number_of_answer_options
    errors.add(:answer_options, "should be at least 2 options") if self.answer_options.length < 2
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :polls
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  def new
    @poll = Poll.find_by(uuid: params[:uuid])
  end

  def create
    @poll = Poll.find(params['answer']['poll_id'])
    authorize @poll, :vote?

    @answer = Answer.new(answer_params.merge(user: current_user))
    if @answer.save
      flash[:success] = 'Thank you! You successfully voted!'
      redirect_to polls_path
    else
      render 'new'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:option, :poll_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_poll, only: [:show, :edit, :destroy]

  def index
    @polls = current_user.polls
  end

  def show
    authorize @poll
    @answers_count = @poll.answers.select(:option).group(:option).count
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.new(params_with_answer_option_as_array.merge(user: current_user))
    if @poll.save
      redirect_to polls_path
    else
      render 'new'
    end
  end

  def edit
    authorize @poll
  end

  def update
    @poll = Poll.find(params[:id])
    authorize @poll
    if @poll.update_attributes(params_with_answer_option_as_array)
      redirect_to @poll
    else
      render 'edit'
    end
  end

  def destroy
    @poll.destroy
    redirect_to polls_path
  end

  private

  def find_poll
    @poll = Poll.find(params[:id])
  end

  def params_with_answer_option_as_array
    attributes = poll_params.dup
    if attributes[:answer_options]
      attributes[:answer_options] = attributes[:answer_options].values.reject { |o| o.empty? }
    end
    attributes
  end

  def poll_params
    params.require(:poll).permit(:title, answer_options: {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-primary"
      when :success then "alert alert-success"
      when :error then "alert alert-danger"
      when :alert then "alert alert-warning"
    end
  end
end

app/helpers/polls_helper.rb
module PollsHelper
  def votes_amount(answers, index)
    "#{pluralize(answers[index] ||= 0, 'vote')}"
  end
end

app/views/answers/_new_vote.html.haml
- if policy(poll).vote?
  %h3= poll.title
  = form_for :answer, url: { action: 'create' } do |f|
    = f.hidden_field :poll_id, value: @poll.id
    = f.radio_button :option, 0, checked: true
    = poll.answer_options[0]
    %br
    - poll.answer_options[1..-1].each_with_index do |option, index|
      = f.radio_button :option, index + 1
      = option
      %br
    = f.submit "Vote"
- else
  %h3 You can't vote again!

app/views/answers/new.html.haml
- if @poll
  = render 'new_vote', poll: @poll
- else
  %h3 Could not find the poll

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container
    .navbar-brand
      = link_to "Home", root_path
    %nav
      %ul.nav.navbar-nav.mr-auto.navbar-right
        - if current_user
          = link_to "Log out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Log in", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ElopagePollApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =render('layouts/header')

    .container
      - flash.each do |key, value|
        %div{:class => "#{flash_class(key)}"}
          = value
      = yield

app/views/polls/_answer_input.html.haml
.form-group.row.answer
  .col-sm-10
    = text_field_tag "poll[answer_options][answer#{answer_number}]", answer, class: 'form-control'
  .col-sm-2
    = link_to 'Delete', '#', class: 'delete-answer'

app/views/polls/_default_answer_options.html.haml
- 2.times do |i|
  = render 'answer_input', answer: '', answer_number: i

app/views/polls/_errors.html.haml
%h4.text-danger Errors:
%p
- poll.errors.full_messages.each do |message|
  %span.text-danger= message
  %br

app/views/polls/_form.html.haml
.row
  .col-md-12.col-md-offset-6
    - if poll.errors.any?
      = render 'errors', poll: poll
    = form_for poll, url: { action: action }, html: {class: 'form-control'} do |f|
      .form-group
        = f.label 'Title'
        = f.text_field :title, class: 'form-control'
      %h4 Answers
      #answers
        - if poll.answer_options.present?
          - poll.answer_options.each_with_index do |answer, index|
            = render 'answer_input', answer_number: index, answer: answer
        - else
          = render 'default_answer_options'
      = f.submit "Save"
      = button_tag("Add option", id: 'add')

app/views/polls/edit.html.haml
%h1 Edit poll
= render 'form', poll: @poll, action: 'update', answers_array: @poll.answer_options

app/views/polls/index.html.haml
%h1 All polls
%p= link_to "Add new poll", new_poll_path
- @polls.each do |p|
  .container.jumbotron
    %h2= link_to p.title, p
    .container
      .form-row
        .container.col-md-6
          - if policy(p).edit?
            = link_to "Edit", edit_poll_path(p)
        .container.col-md-6
          = link_to "Delete", p, method: :delete

app/views/polls/new.html.haml
%h1 Create new poll
= render 'form', poll: @poll, action: 'create'

app/views/polls/show.html.haml
%h1 About poll
%h2 #{@poll.title}
%ul
  - @poll.answer_options.each_with_index do |option, index|
    %li
      = "#{option} - #{votes_amount(@answers_count, index)}"
%h5= link_to vote_url(uuid: @poll.uuid), vote_path(uuid: @poll.uuid)
- if policy(@poll).edit?
  %p= link_to "Edit", edit_poll_path(@poll)
%p= link_to "Delete", @poll, method: :delete